[binaries]
# Replace the paths with the actual paths to your NDK toolchain
root = '/Users/mord/w/torrent/android-toolchain/'
c = root + 'bin/aarch64-linux-android21-clang'
cpp = root + 'bin/aarch64-linux-android21-clang++'
ar = root + 'bin/llvm-ar'
strip = root + 'bin/llvm-strip'
pkg-config = '/usr/local/bin/pkg-config'
# exe_wrapper is typically not needed for Android builds unless running tests on host via emulator

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[built-in options]
default_library = 'static'

# not work
[properties]
crypto = 'openssl'

# not work
[project options]
crypto = 'openssl'
