name: shawndown
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-3.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  libtorrent:
    path: ../libtorrent_dart
  url_launcher: ^6.1.7
  clipboard: ^0.1.3
  path: ^1.8.2
  flutter_window_close: ^0.2.2
  scoped_model: ^2.0.0
  system_tray: ^2.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/app.ico
    - assets/app_icon_32.png
