// generated by gen_alerts.dart

#include "libtorrent.h"

#include "libtorrent/session.hpp"
#include "libtorrent/magnet_uri.hpp"
#include "libtorrent/torrent_handle.hpp"
#include "libtorrent/read_resume_data.hpp"
#include "libtorrent/write_resume_data.hpp"
#include "libtorrent/session_stats.hpp"
#include "libtorrent/alert_types.hpp"

extern "C" {

torrent_removed_alert* Alert2torrent_removed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_removed_alert*>(
      lt::alert_cast<lt::torrent_removed_alert>(a)
    );
}

// info_hash_t torrent_removed_alert_info_hashes(torrent_removed_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_removed_alert*>(out);
//   return a->info_hashes;
// }
read_piece_alert* Alert2read_piece_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<read_piece_alert*>(
      lt::alert_cast<lt::read_piece_alert>(a)
    );
}

// error_code read_piece_alert_error(read_piece_alert* out) {
//   auto* a = reinterpret_cast<lt::read_piece_alert*>(out);
//   return a->error;
// }
// boost::shared_array<char> read_piece_alert_buffer(read_piece_alert* out) {
//   auto* a = reinterpret_cast<lt::read_piece_alert*>(out);
//   return a->buffer;
// }
piece_index_t read_piece_alert_piece(read_piece_alert* out) {
  auto* a = reinterpret_cast<lt::read_piece_alert*>(out);
  return a->piece;
}
int read_piece_alert_size(read_piece_alert* out) {
  auto* a = reinterpret_cast<lt::read_piece_alert*>(out);
  return a->size;
}
file_completed_alert* Alert2file_completed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_completed_alert*>(
      lt::alert_cast<lt::file_completed_alert>(a)
    );
}

file_index_t file_completed_alert_index(file_completed_alert* out) {
  auto* a = reinterpret_cast<lt::file_completed_alert*>(out);
  return a->index;
}
file_renamed_alert* Alert2file_renamed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_renamed_alert*>(
      lt::alert_cast<lt::file_renamed_alert>(a)
    );
}

char const* file_renamed_alert_new_name(file_renamed_alert* out) {
  auto* a = reinterpret_cast<lt::file_renamed_alert*>(out);
  return a->new_name();
}
char const* file_renamed_alert_old_name(file_renamed_alert* out) {
  auto* a = reinterpret_cast<lt::file_renamed_alert*>(out);
  return a->old_name();
}
file_index_t file_renamed_alert_index(file_renamed_alert* out) {
  auto* a = reinterpret_cast<lt::file_renamed_alert*>(out);
  return a->index;
}
file_rename_failed_alert* Alert2file_rename_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_rename_failed_alert*>(
      lt::alert_cast<lt::file_rename_failed_alert>(a)
    );
}

file_index_t file_rename_failed_alert_index(file_rename_failed_alert* out) {
  auto* a = reinterpret_cast<lt::file_rename_failed_alert*>(out);
  return a->index;
}
// error_code file_rename_failed_alert_error(file_rename_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::file_rename_failed_alert*>(out);
//   return a->error;
// }
performance_alert* Alert2performance_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<performance_alert*>(
      lt::alert_cast<lt::performance_alert>(a)
    );
}

// performance_warning_t performance_alert_warning_code(performance_alert* out) {
//   auto* a = reinterpret_cast<lt::performance_alert*>(out);
//   return a->warning_code;
// }
state_changed_alert* Alert2state_changed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<state_changed_alert*>(
      lt::alert_cast<lt::state_changed_alert>(a)
    );
}

// torrent_status::state_t state_changed_alert_state(state_changed_alert* out) {
//   auto* a = reinterpret_cast<lt::state_changed_alert*>(out);
//   return a->state;
// }
// torrent_status::state_t state_changed_alert_prev_state(state_changed_alert* out) {
//   auto* a = reinterpret_cast<lt::state_changed_alert*>(out);
//   return a->prev_state;
// }
tracker_error_alert* Alert2tracker_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<tracker_error_alert*>(
      lt::alert_cast<lt::tracker_error_alert>(a)
    );
}

int tracker_error_alert_times_in_row(tracker_error_alert* out) {
  auto* a = reinterpret_cast<lt::tracker_error_alert*>(out);
  return a->times_in_row;
}
// error_code tracker_error_alert_error(tracker_error_alert* out) {
//   auto* a = reinterpret_cast<lt::tracker_error_alert*>(out);
//   return a->error;
// }
uint8_t tracker_error_alert_op(tracker_error_alert* out) {
  auto* a = reinterpret_cast<lt::tracker_error_alert*>(out);
  return (uint8_t)a->op;
}
char const* tracker_error_alert_failure_reason(tracker_error_alert* out) {
  auto* a = reinterpret_cast<lt::tracker_error_alert*>(out);
  return a->failure_reason();
}
scrape_reply_alert* Alert2scrape_reply_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<scrape_reply_alert*>(
      lt::alert_cast<lt::scrape_reply_alert>(a)
    );
}

int scrape_reply_alert_incomplete(scrape_reply_alert* out) {
  auto* a = reinterpret_cast<lt::scrape_reply_alert*>(out);
  return a->incomplete;
}
int scrape_reply_alert_complete(scrape_reply_alert* out) {
  auto* a = reinterpret_cast<lt::scrape_reply_alert*>(out);
  return a->complete;
}
scrape_failed_alert* Alert2scrape_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<scrape_failed_alert*>(
      lt::alert_cast<lt::scrape_failed_alert>(a)
    );
}

// error_code scrape_failed_alert_error(scrape_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::scrape_failed_alert*>(out);
//   return a->error;
// }
char const* scrape_failed_alert_error_message(scrape_failed_alert* out) {
  auto* a = reinterpret_cast<lt::scrape_failed_alert*>(out);
  return a->error_message();
}
torrent_finished_alert* Alert2torrent_finished_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_finished_alert*>(
      lt::alert_cast<lt::torrent_finished_alert>(a)
    );
}

storage_moved_alert* Alert2storage_moved_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<storage_moved_alert*>(
      lt::alert_cast<lt::storage_moved_alert>(a)
    );
}

char const* storage_moved_alert_storage_path(storage_moved_alert* out) {
  auto* a = reinterpret_cast<lt::storage_moved_alert*>(out);
  return a->storage_path();
}
char const* storage_moved_alert_old_path(storage_moved_alert* out) {
  auto* a = reinterpret_cast<lt::storage_moved_alert*>(out);
  return a->old_path();
}
storage_moved_failed_alert* Alert2storage_moved_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<storage_moved_failed_alert*>(
      lt::alert_cast<lt::storage_moved_failed_alert>(a)
    );
}

// error_code storage_moved_failed_alert_error(storage_moved_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::storage_moved_failed_alert*>(out);
//   return a->error;
// }
char const* storage_moved_failed_alert_file_path(storage_moved_failed_alert* out) {
  auto* a = reinterpret_cast<lt::storage_moved_failed_alert*>(out);
  return a->file_path();
}
uint8_t storage_moved_failed_alert_op(storage_moved_failed_alert* out) {
  auto* a = reinterpret_cast<lt::storage_moved_failed_alert*>(out);
  return (uint8_t)a->op;
}
torrent_deleted_alert* Alert2torrent_deleted_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_deleted_alert*>(
      lt::alert_cast<lt::torrent_deleted_alert>(a)
    );
}

// info_hash_t torrent_deleted_alert_info_hashes(torrent_deleted_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_deleted_alert*>(out);
//   return a->info_hashes;
// }
torrent_delete_failed_alert* Alert2torrent_delete_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_delete_failed_alert*>(
      lt::alert_cast<lt::torrent_delete_failed_alert>(a)
    );
}

// error_code torrent_delete_failed_alert_error(torrent_delete_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_delete_failed_alert*>(out);
//   return a->error;
// }
// info_hash_t torrent_delete_failed_alert_info_hashes(torrent_delete_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_delete_failed_alert*>(out);
//   return a->info_hashes;
// }
save_resume_data_alert* Alert2save_resume_data_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<save_resume_data_alert*>(
      lt::alert_cast<lt::save_resume_data_alert>(a)
    );
}

// add_torrent_params save_resume_data_alert_params(save_resume_data_alert* out) {
//   auto* a = reinterpret_cast<lt::save_resume_data_alert*>(out);
//   return a->params;
// }
save_resume_data_failed_alert* Alert2save_resume_data_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<save_resume_data_failed_alert*>(
      lt::alert_cast<lt::save_resume_data_failed_alert>(a)
    );
}

// error_code save_resume_data_failed_alert_error(save_resume_data_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::save_resume_data_failed_alert*>(out);
//   return a->error;
// }
torrent_paused_alert* Alert2torrent_paused_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_paused_alert*>(
      lt::alert_cast<lt::torrent_paused_alert>(a)
    );
}

torrent_resumed_alert* Alert2torrent_resumed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_resumed_alert*>(
      lt::alert_cast<lt::torrent_resumed_alert>(a)
    );
}

torrent_checked_alert* Alert2torrent_checked_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_checked_alert*>(
      lt::alert_cast<lt::torrent_checked_alert>(a)
    );
}

file_error_alert* Alert2file_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_error_alert*>(
      lt::alert_cast<lt::file_error_alert>(a)
    );
}

listen_failed_alert* Alert2listen_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<listen_failed_alert*>(
      lt::alert_cast<lt::listen_failed_alert>(a)
    );
}

// error_code listen_failed_alert_error(listen_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::listen_failed_alert*>(out);
//   return a->error;
// }
char const* listen_failed_alert_listen_interface(listen_failed_alert* out) {
  auto* a = reinterpret_cast<lt::listen_failed_alert*>(out);
  return a->listen_interface();
}
uint8_t listen_failed_alert_op(listen_failed_alert* out) {
  auto* a = reinterpret_cast<lt::listen_failed_alert*>(out);
  return (uint8_t)a->op;
}
int listen_failed_alert_port(listen_failed_alert* out) {
  auto* a = reinterpret_cast<lt::listen_failed_alert*>(out);
  return a->port;
}
listen_succeeded_alert* Alert2listen_succeeded_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<listen_succeeded_alert*>(
      lt::alert_cast<lt::listen_succeeded_alert>(a)
    );
}

int listen_succeeded_alert_port(listen_succeeded_alert* out) {
  auto* a = reinterpret_cast<lt::listen_succeeded_alert*>(out);
  return a->port;
}
uint8_t listen_succeeded_alert_socket_type(listen_succeeded_alert* out) {
  auto* a = reinterpret_cast<lt::listen_succeeded_alert*>(out);
  return (uint8_t)a->socket_type;
}
fastresume_rejected_alert* Alert2fastresume_rejected_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<fastresume_rejected_alert*>(
      lt::alert_cast<lt::fastresume_rejected_alert>(a)
    );
}

// error_code fastresume_rejected_alert_error(fastresume_rejected_alert* out) {
//   auto* a = reinterpret_cast<lt::fastresume_rejected_alert*>(out);
//   return a->error;
// }
char const* fastresume_rejected_alert_file_path(fastresume_rejected_alert* out) {
  auto* a = reinterpret_cast<lt::fastresume_rejected_alert*>(out);
  return a->file_path();
}
operation_t fastresume_rejected_alert_op(fastresume_rejected_alert* out) {
  auto* a = reinterpret_cast<lt::fastresume_rejected_alert*>(out);
  return (uint8_t)a->op;
}
cache_flushed_alert* Alert2cache_flushed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<cache_flushed_alert*>(
      lt::alert_cast<lt::cache_flushed_alert>(a)
    );
}

torrent_error_alert* Alert2torrent_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_error_alert*>(
      lt::alert_cast<lt::torrent_error_alert>(a)
    );
}

// error_code torrent_error_alert_error(torrent_error_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_error_alert*>(out);
//   return a->error;
// }
char const* torrent_error_alert_filename(torrent_error_alert* out) {
  auto* a = reinterpret_cast<lt::torrent_error_alert*>(out);
  return a->filename();
}
torrent_need_cert_alert* Alert2torrent_need_cert_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_need_cert_alert*>(
      lt::alert_cast<lt::torrent_need_cert_alert>(a)
    );
}

add_torrent_alert* Alert2add_torrent_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<add_torrent_alert*>(
      lt::alert_cast<lt::add_torrent_alert>(a)
    );
}

// add_torrent_params add_torrent_alert_params(add_torrent_alert* out) {
//   auto* a = reinterpret_cast<lt::add_torrent_alert*>(out);
//   return a->params;
// }
// error_code add_torrent_alert_error(add_torrent_alert* out) {
//   auto* a = reinterpret_cast<lt::add_torrent_alert*>(out);
//   return a->error;
// }
state_update_alert* Alert2state_update_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<state_update_alert*>(
      lt::alert_cast<lt::state_update_alert>(a)
    );
}

// std::vector<torrent_status> state_update_alert_status(state_update_alert* out) {
//   auto* a = reinterpret_cast<lt::state_update_alert*>(out);
//   return a->status;
// }
session_stats_alert* Alert2session_stats_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<session_stats_alert*>(
      lt::alert_cast<lt::session_stats_alert>(a)
    );
}

// span<std::int64_t const> session_stats_alert_counters(session_stats_alert* out) {
//   auto* a = reinterpret_cast<lt::session_stats_alert*>(out);
//   return a->counters();
// }
dht_immutable_item_alert* Alert2dht_immutable_item_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_immutable_item_alert*>(
      lt::alert_cast<lt::dht_immutable_item_alert>(a)
    );
}

// sha1_hash dht_immutable_item_alert_target(dht_immutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_immutable_item_alert*>(out);
//   return a->target;
// }
// entry dht_immutable_item_alert_item(dht_immutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_immutable_item_alert*>(out);
//   return a->item;
// }
dht_mutable_item_alert* Alert2dht_mutable_item_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_mutable_item_alert*>(
      lt::alert_cast<lt::dht_mutable_item_alert>(a)
    );
}

// std::array<char, 32> dht_mutable_item_alert_key(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->key;
// }
// std::array<char, 64> dht_mutable_item_alert_signature(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->signature;
// }
// std::int64_t dht_mutable_item_alert_seq(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->seq;
// }
// std::string dht_mutable_item_alert_salt(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->salt;
// }
// entry dht_mutable_item_alert_item(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->item;
// }
// bool dht_mutable_item_alert_authoritative(dht_mutable_item_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_mutable_item_alert*>(out);
//   return a->authoritative;
// }
dht_direct_response_alert* Alert2dht_direct_response_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_direct_response_alert*>(
      lt::alert_cast<lt::dht_direct_response_alert>(a)
    );
}

// client_data_t dht_direct_response_alert_userdata(dht_direct_response_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_direct_response_alert*>(out);
//   return a->userdata;
// }
// aux::noexcept_movable<udp::endpoint> dht_direct_response_alert_endpoint(dht_direct_response_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_direct_response_alert*>(out);
//   return a->endpoint;
// }
// bdecode_node response() dht_direct_response_alert_const(dht_direct_response_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_direct_response_alert*>(out);
//   return a->const;
// }
alerts_dropped_alert* Alert2alerts_dropped_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<alerts_dropped_alert*>(
      lt::alert_cast<lt::alerts_dropped_alert>(a)
    );
}

// std::bitset<abi_alert_count> alerts_dropped_alert_dropped_alerts(alerts_dropped_alert* out) {
//   auto* a = reinterpret_cast<lt::alerts_dropped_alert*>(out);
//   return a->dropped_alerts;
// }
torrent_conflict_alert* Alert2torrent_conflict_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_conflict_alert*>(
      lt::alert_cast<lt::torrent_conflict_alert>(a)
    );
}

// torrent_handle torrent_conflict_alert_conflicting_torrent(torrent_conflict_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_conflict_alert*>(out);
//   return a->conflicting_torrent;
// }
// std::shared_ptr<torrent_info> torrent_conflict_alert_metadata(torrent_conflict_alert* out) {
//   auto* a = reinterpret_cast<lt::torrent_conflict_alert*>(out);
//   return a->metadata;
// }
peer_info_alert* Alert2peer_info_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_info_alert*>(
      lt::alert_cast<lt::peer_info_alert>(a)
    );
}

// std::vector<lt::peer_info> peer_info_alert_peer_info(peer_info_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_info_alert*>(out);
//   return a->peer_info;
// }
file_progress_alert* Alert2file_progress_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_progress_alert*>(
      lt::alert_cast<lt::file_progress_alert>(a)
    );
}

// aux::vector<std::int64_t, file_index_t> file_progress_alert_files(file_progress_alert* out) {
//   auto* a = reinterpret_cast<lt::file_progress_alert*>(out);
//   return a->files;
// }
piece_info_alert* Alert2piece_info_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<piece_info_alert*>(
      lt::alert_cast<lt::piece_info_alert>(a)
    );
}

// std::vector<partial_piece_info> piece_info_alert_piece_info(piece_info_alert* out) {
//   auto* a = reinterpret_cast<lt::piece_info_alert*>(out);
//   return a->piece_info;
// }
// std::vector<block_info> piece_info_alert_block_data(piece_info_alert* out) {
//   auto* a = reinterpret_cast<lt::piece_info_alert*>(out);
//   return a->block_data;
// }
tracker_list_alert* Alert2tracker_list_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<tracker_list_alert*>(
      lt::alert_cast<lt::tracker_list_alert>(a)
    );
}

// std::vector<announce_entry> tracker_list_alert_trackers(tracker_list_alert* out) {
//   auto* a = reinterpret_cast<lt::tracker_list_alert*>(out);
//   return a->trackers;
// }
piece_availability_alert* Alert2piece_availability_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<piece_availability_alert*>(
      lt::alert_cast<lt::piece_availability_alert>(a)
    );
}

// std::vector<int> piece_availability_alert_piece_availability(piece_availability_alert* out) {
//   auto* a = reinterpret_cast<lt::piece_availability_alert*>(out);
//   return a->piece_availability;
// }
tracker_warning_alert* Alert2tracker_warning_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<tracker_warning_alert*>(
      lt::alert_cast<lt::tracker_warning_alert>(a)
    );
}

char const* tracker_warning_alert_warning_message(tracker_warning_alert* out) {
  auto* a = reinterpret_cast<lt::tracker_warning_alert*>(out);
  return a->warning_message();
}
tracker_reply_alert* Alert2tracker_reply_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<tracker_reply_alert*>(
      lt::alert_cast<lt::tracker_reply_alert>(a)
    );
}

int tracker_reply_alert_num_peers(tracker_reply_alert* out) {
  auto* a = reinterpret_cast<lt::tracker_reply_alert*>(out);
  return a->num_peers;
}
dht_reply_alert* Alert2dht_reply_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_reply_alert*>(
      lt::alert_cast<lt::dht_reply_alert>(a)
    );
}

int dht_reply_alert_num_peers(dht_reply_alert* out) {
  auto* a = reinterpret_cast<lt::dht_reply_alert*>(out);
  return a->num_peers;
}
tracker_announce_alert* Alert2tracker_announce_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<tracker_announce_alert*>(
      lt::alert_cast<lt::tracker_announce_alert>(a)
    );
}

// event_t tracker_announce_alert_event(tracker_announce_alert* out) {
//   auto* a = reinterpret_cast<lt::tracker_announce_alert*>(out);
//   return a->event;
// }
hash_failed_alert* Alert2hash_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<hash_failed_alert*>(
      lt::alert_cast<lt::hash_failed_alert>(a)
    );
}

piece_index_t hash_failed_alert_piece_index(hash_failed_alert* out) {
  auto* a = reinterpret_cast<lt::hash_failed_alert*>(out);
  return a->piece_index;
}
peer_ban_alert* Alert2peer_ban_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_ban_alert*>(
      lt::alert_cast<lt::peer_ban_alert>(a)
    );
}

peer_unsnubbed_alert* Alert2peer_unsnubbed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_unsnubbed_alert*>(
      lt::alert_cast<lt::peer_unsnubbed_alert>(a)
    );
}

peer_snubbed_alert* Alert2peer_snubbed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_snubbed_alert*>(
      lt::alert_cast<lt::peer_snubbed_alert>(a)
    );
}

peer_error_alert* Alert2peer_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_error_alert*>(
      lt::alert_cast<lt::peer_error_alert>(a)
    );
}

operation_t peer_error_alert_op(peer_error_alert* out) {
  auto* a = reinterpret_cast<lt::peer_error_alert*>(out);
  return (uint8_t)a->op;
}
// error_code peer_error_alert_error(peer_error_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_error_alert*>(out);
//   return a->error;
// }
peer_connect_alert* Alert2peer_connect_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_connect_alert*>(
      lt::alert_cast<lt::peer_connect_alert>(a)
    );
}

// direction_t peer_connect_alert_direction(peer_connect_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_connect_alert*>(out);
//   return a->direction;
// }
socket_type_t peer_connect_alert_socket_type(peer_connect_alert* out) {
  auto* a = reinterpret_cast<lt::peer_connect_alert*>(out);
  return (uint8_t)a->socket_type;
}
peer_disconnected_alert* Alert2peer_disconnected_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_disconnected_alert*>(
      lt::alert_cast<lt::peer_disconnected_alert>(a)
    );
}

socket_type_t peer_disconnected_alert_socket_type(peer_disconnected_alert* out) {
  auto* a = reinterpret_cast<lt::peer_disconnected_alert*>(out);
  return (uint8_t)a->socket_type;
}
operation_t peer_disconnected_alert_op(peer_disconnected_alert* out) {
  auto* a = reinterpret_cast<lt::peer_disconnected_alert*>(out);
  return (uint8_t)a->op;
}
// error_code peer_disconnected_alert_error(peer_disconnected_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_disconnected_alert*>(out);
//   return a->error;
// }
// close_reason_t peer_disconnected_alert_reason(peer_disconnected_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_disconnected_alert*>(out);
//   return a->reason;
// }
invalid_request_alert* Alert2invalid_request_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<invalid_request_alert*>(
      lt::alert_cast<lt::invalid_request_alert>(a)
    );
}

// peer_request invalid_request_alert_request(invalid_request_alert* out) {
//   auto* a = reinterpret_cast<lt::invalid_request_alert*>(out);
//   return a->request;
// }
// bool invalid_request_alert_we_have(invalid_request_alert* out) {
//   auto* a = reinterpret_cast<lt::invalid_request_alert*>(out);
//   return a->we_have;
// }
// bool invalid_request_alert_peer_interested(invalid_request_alert* out) {
//   auto* a = reinterpret_cast<lt::invalid_request_alert*>(out);
//   return a->peer_interested;
// }
// bool invalid_request_alert_withheld(invalid_request_alert* out) {
//   auto* a = reinterpret_cast<lt::invalid_request_alert*>(out);
//   return a->withheld;
// }
piece_finished_alert* Alert2piece_finished_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<piece_finished_alert*>(
      lt::alert_cast<lt::piece_finished_alert>(a)
    );
}

piece_index_t piece_finished_alert_piece_index(piece_finished_alert* out) {
  auto* a = reinterpret_cast<lt::piece_finished_alert*>(out);
  return a->piece_index;
}
request_dropped_alert* Alert2request_dropped_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<request_dropped_alert*>(
      lt::alert_cast<lt::request_dropped_alert>(a)
    );
}

piece_index_t request_dropped_alert_piece_index(request_dropped_alert* out) {
  auto* a = reinterpret_cast<lt::request_dropped_alert*>(out);
  return a->piece_index;
}
int request_dropped_alert_block_index(request_dropped_alert* out) {
  auto* a = reinterpret_cast<lt::request_dropped_alert*>(out);
  return a->block_index;
}
block_timeout_alert* Alert2block_timeout_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<block_timeout_alert*>(
      lt::alert_cast<lt::block_timeout_alert>(a)
    );
}

piece_index_t block_timeout_alert_piece_index(block_timeout_alert* out) {
  auto* a = reinterpret_cast<lt::block_timeout_alert*>(out);
  return a->piece_index;
}
int block_timeout_alert_block_index(block_timeout_alert* out) {
  auto* a = reinterpret_cast<lt::block_timeout_alert*>(out);
  return a->block_index;
}
block_finished_alert* Alert2block_finished_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<block_finished_alert*>(
      lt::alert_cast<lt::block_finished_alert>(a)
    );
}

piece_index_t block_finished_alert_piece_index(block_finished_alert* out) {
  auto* a = reinterpret_cast<lt::block_finished_alert*>(out);
  return a->piece_index;
}
int block_finished_alert_block_index(block_finished_alert* out) {
  auto* a = reinterpret_cast<lt::block_finished_alert*>(out);
  return a->block_index;
}
block_downloading_alert* Alert2block_downloading_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<block_downloading_alert*>(
      lt::alert_cast<lt::block_downloading_alert>(a)
    );
}

piece_index_t block_downloading_alert_piece_index(block_downloading_alert* out) {
  auto* a = reinterpret_cast<lt::block_downloading_alert*>(out);
  return a->piece_index;
}
int block_downloading_alert_block_index(block_downloading_alert* out) {
  auto* a = reinterpret_cast<lt::block_downloading_alert*>(out);
  return a->block_index;
}
unwanted_block_alert* Alert2unwanted_block_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<unwanted_block_alert*>(
      lt::alert_cast<lt::unwanted_block_alert>(a)
    );
}

piece_index_t unwanted_block_alert_piece_index(unwanted_block_alert* out) {
  auto* a = reinterpret_cast<lt::unwanted_block_alert*>(out);
  return a->piece_index;
}
int unwanted_block_alert_block_index(unwanted_block_alert* out) {
  auto* a = reinterpret_cast<lt::unwanted_block_alert*>(out);
  return a->block_index;
}
url_seed_alert* Alert2url_seed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<url_seed_alert*>(
      lt::alert_cast<lt::url_seed_alert>(a)
    );
}

char const* url_seed_alert_server_url(url_seed_alert* out) {
  auto* a = reinterpret_cast<lt::url_seed_alert*>(out);
  return a->server_url();
}
// error_code url_seed_alert_error(url_seed_alert* out) {
//   auto* a = reinterpret_cast<lt::url_seed_alert*>(out);
//   return a->error;
// }
char const* url_seed_alert_error_message(url_seed_alert* out) {
  auto* a = reinterpret_cast<lt::url_seed_alert*>(out);
  return a->error_message();
}
metadata_failed_alert* Alert2metadata_failed_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<metadata_failed_alert*>(
      lt::alert_cast<lt::metadata_failed_alert>(a)
    );
}

// error_code metadata_failed_alert_error(metadata_failed_alert* out) {
//   auto* a = reinterpret_cast<lt::metadata_failed_alert*>(out);
//   return a->error;
// }
metadata_received_alert* Alert2metadata_received_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<metadata_received_alert*>(
      lt::alert_cast<lt::metadata_received_alert>(a)
    );
}

udp_error_alert* Alert2udp_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<udp_error_alert*>(
      lt::alert_cast<lt::udp_error_alert>(a)
    );
}

uint8_t udp_error_alert_operation(udp_error_alert* out) {
  auto* a = reinterpret_cast<lt::udp_error_alert*>(out);
  return (uint8_t)a->operation;
}
// error_code udp_error_alert_error(udp_error_alert* out) {
//   auto* a = reinterpret_cast<lt::udp_error_alert*>(out);
//   return a->error;
// }
external_ip_alert* Alert2external_ip_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<external_ip_alert*>(
      lt::alert_cast<lt::external_ip_alert>(a)
    );
}

portmap_error_alert* Alert2portmap_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<portmap_error_alert*>(
      lt::alert_cast<lt::portmap_error_alert>(a)
    );
}

// port_mapping_t portmap_error_alert_mapping(portmap_error_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_error_alert*>(out);
//   return a->mapping;
// }
// portmap_transport portmap_error_alert_map_transport(portmap_error_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_error_alert*>(out);
//   return a->map_transport;
// }
// aux::noexcept_movable<address> portmap_error_alert_local_address(portmap_error_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_error_alert*>(out);
//   return a->local_address;
// }
// error_code portmap_error_alert_error(portmap_error_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_error_alert*>(out);
//   return a->error;
// }
portmap_alert* Alert2portmap_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<portmap_alert*>(
      lt::alert_cast<lt::portmap_alert>(a)
    );
}

// port_mapping_t portmap_alert_mapping(portmap_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_alert*>(out);
//   return a->mapping;
// }
int portmap_alert_external_port(portmap_alert* out) {
  auto* a = reinterpret_cast<lt::portmap_alert*>(out);
  return a->external_port;
}
// portmap_transport portmap_alert_map_transport(portmap_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_alert*>(out);
//   return a->map_transport;
// }
// aux::noexcept_movable<address> portmap_alert_local_address(portmap_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_alert*>(out);
//   return a->local_address;
// }
portmap_log_alert* Alert2portmap_log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<portmap_log_alert*>(
      lt::alert_cast<lt::portmap_log_alert>(a)
    );
}

// portmap_transport portmap_log_alert_map_transport(portmap_log_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_log_alert*>(out);
//   return a->map_transport;
// }
// aux::noexcept_movable<address> portmap_log_alert_local_address(portmap_log_alert* out) {
//   auto* a = reinterpret_cast<lt::portmap_log_alert*>(out);
//   return a->local_address;
// }
char const* portmap_log_alert_log_message(portmap_log_alert* out) {
  auto* a = reinterpret_cast<lt::portmap_log_alert*>(out);
  return a->log_message();
}
peer_blocked_alert* Alert2peer_blocked_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_blocked_alert*>(
      lt::alert_cast<lt::peer_blocked_alert>(a)
    );
}

int peer_blocked_alert_reason(peer_blocked_alert* out) {
  auto* a = reinterpret_cast<lt::peer_blocked_alert*>(out);
  return a->reason;
}
dht_announce_alert* Alert2dht_announce_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_announce_alert*>(
      lt::alert_cast<lt::dht_announce_alert>(a)
    );
}

// aux::noexcept_movable<address> dht_announce_alert_ip(dht_announce_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_announce_alert*>(out);
//   return a->ip;
// }
int dht_announce_alert_port(dht_announce_alert* out) {
  auto* a = reinterpret_cast<lt::dht_announce_alert*>(out);
  return a->port;
}
// sha1_hash dht_announce_alert_info_hash(dht_announce_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_announce_alert*>(out);
//   return a->info_hash;
// }
dht_get_peers_alert* Alert2dht_get_peers_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_get_peers_alert*>(
      lt::alert_cast<lt::dht_get_peers_alert>(a)
    );
}

// sha1_hash dht_get_peers_alert_info_hash(dht_get_peers_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_get_peers_alert*>(out);
//   return a->info_hash;
// }
stats_alert* Alert2stats_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<stats_alert*>(
      lt::alert_cast<lt::stats_alert>(a)
    );
}

// std::array<int, num_channels> stats_alert_transferred(stats_alert* out) {
//   auto* a = reinterpret_cast<lt::stats_alert*>(out);
//   return a->transferred;
// }
int stats_alert_interval(stats_alert* out) {
  auto* a = reinterpret_cast<lt::stats_alert*>(out);
  return a->interval;
}
lsd_peer_alert* Alert2lsd_peer_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<lsd_peer_alert*>(
      lt::alert_cast<lt::lsd_peer_alert>(a)
    );
}

trackerid_alert* Alert2trackerid_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<trackerid_alert*>(
      lt::alert_cast<lt::trackerid_alert>(a)
    );
}

char const* trackerid_alert_tracker_id(trackerid_alert* out) {
  auto* a = reinterpret_cast<lt::trackerid_alert*>(out);
  return a->tracker_id();
}
dht_bootstrap_alert* Alert2dht_bootstrap_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_bootstrap_alert*>(
      lt::alert_cast<lt::dht_bootstrap_alert>(a)
    );
}

incoming_connection_alert* Alert2incoming_connection_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<incoming_connection_alert*>(
      lt::alert_cast<lt::incoming_connection_alert>(a)
    );
}

socket_type_t incoming_connection_alert_socket_type(incoming_connection_alert* out) {
  auto* a = reinterpret_cast<lt::incoming_connection_alert*>(out);
  return (uint8_t)a->socket_type;
}
// aux::noexcept_movable<tcp::endpoint> incoming_connection_alert_endpoint(incoming_connection_alert* out) {
//   auto* a = reinterpret_cast<lt::incoming_connection_alert*>(out);
//   return a->endpoint;
// }
dht_error_alert* Alert2dht_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_error_alert*>(
      lt::alert_cast<lt::dht_error_alert>(a)
    );
}

// error_code dht_error_alert_error(dht_error_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_error_alert*>(out);
//   return a->error;
// }
operation_t dht_error_alert_op(dht_error_alert* out) {
  auto* a = reinterpret_cast<lt::dht_error_alert*>(out);
  return (uint8_t)a->op;
}
dht_put_alert* Alert2dht_put_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_put_alert*>(
      lt::alert_cast<lt::dht_put_alert>(a)
    );
}

// sha1_hash dht_put_alert_target(dht_put_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
//   return a->target;
// }
// std::array<char, 32> dht_put_alert_public_key(dht_put_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
//   return a->public_key;
// }
// std::array<char, 64> dht_put_alert_signature(dht_put_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
//   return a->signature;
// }
// std::string dht_put_alert_salt(dht_put_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
//   return a->salt;
// }
// std::int64_t dht_put_alert_seq(dht_put_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
//   return a->seq;
// }
int dht_put_alert_num_success(dht_put_alert* out) {
  auto* a = reinterpret_cast<lt::dht_put_alert*>(out);
  return a->num_success;
}
i2p_alert* Alert2i2p_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<i2p_alert*>(
      lt::alert_cast<lt::i2p_alert>(a)
    );
}

// error_code i2p_alert_error(i2p_alert* out) {
//   auto* a = reinterpret_cast<lt::i2p_alert*>(out);
//   return a->error;
// }
dht_outgoing_get_peers_alert* Alert2dht_outgoing_get_peers_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_outgoing_get_peers_alert*>(
      lt::alert_cast<lt::dht_outgoing_get_peers_alert>(a)
    );
}

// sha1_hash dht_outgoing_get_peers_alert_info_hash(dht_outgoing_get_peers_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_outgoing_get_peers_alert*>(out);
//   return a->info_hash;
// }
// sha1_hash dht_outgoing_get_peers_alert_obfuscated_info_hash(dht_outgoing_get_peers_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_outgoing_get_peers_alert*>(out);
//   return a->obfuscated_info_hash;
// }
// aux::noexcept_movable<udp::endpoint> dht_outgoing_get_peers_alert_endpoint(dht_outgoing_get_peers_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_outgoing_get_peers_alert*>(out);
//   return a->endpoint;
// }
log_alert* Alert2log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<log_alert*>(
      lt::alert_cast<lt::log_alert>(a)
    );
}

char const* log_alert_log_message(log_alert* out) {
  auto* a = reinterpret_cast<lt::log_alert*>(out);
  return a->log_message();
}
torrent_log_alert* Alert2torrent_log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<torrent_log_alert*>(
      lt::alert_cast<lt::torrent_log_alert>(a)
    );
}

char const* torrent_log_alert_log_message(torrent_log_alert* out) {
  auto* a = reinterpret_cast<lt::torrent_log_alert*>(out);
  return a->log_message();
}
peer_log_alert* Alert2peer_log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<peer_log_alert*>(
      lt::alert_cast<lt::peer_log_alert>(a)
    );
}

char const* peer_log_alert_event_type(peer_log_alert* out) {
  auto* a = reinterpret_cast<lt::peer_log_alert*>(out);
  return a->event_type;
}
// direction_t peer_log_alert_direction(peer_log_alert* out) {
//   auto* a = reinterpret_cast<lt::peer_log_alert*>(out);
//   return a->direction;
// }
char const* peer_log_alert_log_message(peer_log_alert* out) {
  auto* a = reinterpret_cast<lt::peer_log_alert*>(out);
  return a->log_message();
}
lsd_error_alert* Alert2lsd_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<lsd_error_alert*>(
      lt::alert_cast<lt::lsd_error_alert>(a)
    );
}

// aux::noexcept_movable<address> lsd_error_alert_local_address(lsd_error_alert* out) {
//   auto* a = reinterpret_cast<lt::lsd_error_alert*>(out);
//   return a->local_address;
// }
// error_code lsd_error_alert_error(lsd_error_alert* out) {
//   auto* a = reinterpret_cast<lt::lsd_error_alert*>(out);
//   return a->error;
// }
dht_stats_alert* Alert2dht_stats_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_stats_alert*>(
      lt::alert_cast<lt::dht_stats_alert>(a)
    );
}

// std::vector<dht_lookup> dht_stats_alert_active_requests(dht_stats_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_stats_alert*>(out);
//   return a->active_requests;
// }
// std::vector<dht_routing_bucket> dht_stats_alert_routing_table(dht_stats_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_stats_alert*>(out);
//   return a->routing_table;
// }
// sha1_hash dht_stats_alert_nid(dht_stats_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_stats_alert*>(out);
//   return a->nid;
// }
// aux::noexcept_movable<udp::endpoint> dht_stats_alert_local_endpoint(dht_stats_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_stats_alert*>(out);
//   return a->local_endpoint;
// }
incoming_request_alert* Alert2incoming_request_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<incoming_request_alert*>(
      lt::alert_cast<lt::incoming_request_alert>(a)
    );
}

// peer_request incoming_request_alert_req(incoming_request_alert* out) {
//   auto* a = reinterpret_cast<lt::incoming_request_alert*>(out);
//   return a->req;
// }
dht_log_alert* Alert2dht_log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_log_alert*>(
      lt::alert_cast<lt::dht_log_alert>(a)
    );
}

char const* dht_log_alert_log_message(dht_log_alert* out) {
  auto* a = reinterpret_cast<lt::dht_log_alert*>(out);
  return a->log_message();
}
// dht_module_t dht_log_alert_module(dht_log_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_log_alert*>(out);
//   return a->module;
// }
dht_pkt_alert* Alert2dht_pkt_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_pkt_alert*>(
      lt::alert_cast<lt::dht_pkt_alert>(a)
    );
}

// span<char const> pkt_buf() dht_pkt_alert_const(dht_pkt_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_pkt_alert*>(out);
//   return a->const;
// }
// direction_t dht_pkt_alert_direction(dht_pkt_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_pkt_alert*>(out);
//   return a->direction;
// }
// aux::noexcept_movable<udp::endpoint> dht_pkt_alert_node(dht_pkt_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_pkt_alert*>(out);
//   return a->node;
// }
dht_get_peers_reply_alert* Alert2dht_get_peers_reply_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_get_peers_reply_alert*>(
      lt::alert_cast<lt::dht_get_peers_reply_alert>(a)
    );
}

// sha1_hash dht_get_peers_reply_alert_info_hash(dht_get_peers_reply_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_get_peers_reply_alert*>(out);
//   return a->info_hash;
// }
int dht_get_peers_reply_alert_num_peers(dht_get_peers_reply_alert* out) {
  auto* a = reinterpret_cast<lt::dht_get_peers_reply_alert*>(out);
  return a->num_peers();
}
// std::vector<tcp::endpoint> dht_get_peers_reply_alert_peers(dht_get_peers_reply_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_get_peers_reply_alert*>(out);
//   return a->peers;
// }
picker_log_alert* Alert2picker_log_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<picker_log_alert*>(
      lt::alert_cast<lt::picker_log_alert>(a)
    );
}

// picker_flags_t picker_log_alert_picker_flags(picker_log_alert* out) {
//   auto* a = reinterpret_cast<lt::picker_log_alert*>(out);
//   return a->picker_flags;
// }
// std::vector<piece_block> picker_log_alert_blocks(picker_log_alert* out) {
//   auto* a = reinterpret_cast<lt::picker_log_alert*>(out);
//   return a->blocks;
// }
session_error_alert* Alert2session_error_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<session_error_alert*>(
      lt::alert_cast<lt::session_error_alert>(a)
    );
}

// error_code session_error_alert_error(session_error_alert* out) {
//   auto* a = reinterpret_cast<lt::session_error_alert*>(out);
//   return a->error;
// }
dht_live_nodes_alert* Alert2dht_live_nodes_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_live_nodes_alert*>(
      lt::alert_cast<lt::dht_live_nodes_alert>(a)
    );
}

// sha1_hash dht_live_nodes_alert_node_id(dht_live_nodes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_live_nodes_alert*>(out);
//   return a->node_id;
// }
int dht_live_nodes_alert_num_nodes(dht_live_nodes_alert* out) {
  auto* a = reinterpret_cast<lt::dht_live_nodes_alert*>(out);
  return a->num_nodes();
}
// std::vector<std::pair<sha1_hash, udp::endpoint>> dht_live_nodes_alert_nodes(dht_live_nodes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_live_nodes_alert*>(out);
//   return a->nodes();
// }
session_stats_header_alert* Alert2session_stats_header_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<session_stats_header_alert*>(
      lt::alert_cast<lt::session_stats_header_alert>(a)
    );
}

dht_sample_infohashes_alert* Alert2dht_sample_infohashes_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<dht_sample_infohashes_alert*>(
      lt::alert_cast<lt::dht_sample_infohashes_alert>(a)
    );
}

// sha1_hash dht_sample_infohashes_alert_node_id(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->node_id;
// }
// aux::noexcept_movable<udp::endpoint> dht_sample_infohashes_alert_endpoint(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->endpoint;
// }
// time_duration const dht_sample_infohashes_alert_interval(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->interval;
// }
// int const dht_sample_infohashes_alert_num_infohashes(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->num_infohashes;
// }
int dht_sample_infohashes_alert_num_samples(dht_sample_infohashes_alert* out) {
  auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
  return a->num_samples();
}
// std::vector<sha1_hash> dht_sample_infohashes_alert_samples(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->samples();
// }
int dht_sample_infohashes_alert_num_nodes(dht_sample_infohashes_alert* out) {
  auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
  return a->num_nodes();
}
// std::vector<std::pair<sha1_hash, udp::endpoint>> dht_sample_infohashes_alert_nodes(dht_sample_infohashes_alert* out) {
//   auto* a = reinterpret_cast<lt::dht_sample_infohashes_alert*>(out);
//   return a->nodes();
// }
block_uploaded_alert* Alert2block_uploaded_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<block_uploaded_alert*>(
      lt::alert_cast<lt::block_uploaded_alert>(a)
    );
}

// int const block_uploaded_alert_block_index(block_uploaded_alert* out) {
//   auto* a = reinterpret_cast<lt::block_uploaded_alert*>(out);
//   return a->block_index;
// }
// piece_index_t const block_uploaded_alert_piece_index(block_uploaded_alert* out) {
//   auto* a = reinterpret_cast<lt::block_uploaded_alert*>(out);
//   return a->piece_index;
// }
socks5_alert* Alert2socks5_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<socks5_alert*>(
      lt::alert_cast<lt::socks5_alert>(a)
    );
}

// error_code socks5_alert_error(socks5_alert* out) {
//   auto* a = reinterpret_cast<lt::socks5_alert*>(out);
//   return a->error;
// }
operation_t socks5_alert_op(socks5_alert* out) {
  auto* a = reinterpret_cast<lt::socks5_alert*>(out);
  return (uint8_t)a->op;
}
// aux::noexcept_movable<tcp::endpoint> socks5_alert_ip(socks5_alert* out) {
//   auto* a = reinterpret_cast<lt::socks5_alert*>(out);
//   return a->ip;
// }
file_prio_alert* Alert2file_prio_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<file_prio_alert*>(
      lt::alert_cast<lt::file_prio_alert>(a)
    );
}

// error_code file_prio_alert_error(file_prio_alert* out) {
//   auto* a = reinterpret_cast<lt::file_prio_alert*>(out);
//   return a->error;
// }
operation_t file_prio_alert_op(file_prio_alert* out) {
  auto* a = reinterpret_cast<lt::file_prio_alert*>(out);
  return (uint8_t)a->op;
}
oversized_file_alert* Alert2oversized_file_alert(Alert* out) {
  auto* a = reinterpret_cast<lt::alert*>(out);
  return reinterpret_cast<oversized_file_alert*>(
      lt::alert_cast<lt::oversized_file_alert>(a)
    );
}

file_index_t oversized_file_alert_reserved(oversized_file_alert* out) {
  auto* a = reinterpret_cast<lt::oversized_file_alert*>(out);
  return a->reserved;
}
} // extern C