name: torrent
description: Implement Torrent in Dart.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  crypto: any
  async:
  clock:
  fake_async:
  sse:
  logging:
  pool:
  stream_channel:
  shelf:
  path:
  # for magnet
  base32:
  convert:


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
